[package]
name = "miami-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
leptos = { version = "0.5.0-rc2", features = ["csr", "nightly"] }
rand = "0.8.5"
stylers = "0.3.2"
